#' Generate Analysis Report
#'
#' @description
#' Generate comprehensive analysis reports in various formats (HTML, PDF, Word).
#'
#' @param data Analysis results data
#' @param output_file Output file path
#' @param output_format Output format: "html", "pdf", "word"
#' @param title Report title
#' @param author Report author
#' @param template Optional custom template
#' @return Path to generated report
#' @export
#'
#' @importFrom utils packageVersion
#'
#' @examples
#' \dontrun{
#' # Generate HTML report
#' result <- analyze_correlation("TP53", "EGFR", "BRCA")
#' generate_report(result, "report.html", "html", "Correlation Analysis")
#' }
generate_report <- function(data,
                            output_file = "report.html",
                            output_format = c("html", "pdf", "word"),
                            title = "ZinaSuite Analysis Report",
                            author = "ZinaSuite User",
                            template = NULL) {
  output_format <- match.arg(output_format)

  # Check required packages
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required. Install with: install.packages('rmarkdown')")
  }

  # Create temporary Rmd file
  temp_rmd <- tempfile(fileext = ".Rmd")

  # Generate Rmd content
  rmd_content <- generate_report_template(data, title, author, output_format)

  # Write to file
  writeLines(rmd_content, temp_rmd)

  # Render report
  output_format_arg <- switch(output_format,
                              "html" = rmarkdown::html_document(),
                              "pdf" = rmarkdown::pdf_document(),
                              "word" = rmarkdown::word_document())

  rmarkdown::render(
    input = temp_rmd,
    output_file = output_file,
    output_format = output_format_arg,
    quiet = TRUE
  )

  # Clean up
  unlink(temp_rmd)

  message("Report generated: ", normalizePath(output_file))
  invisible(output_file)
}

#' Generate Report Template
#'
#' @param data Analysis data
#' @param title Report title
#' @param author Report author
#' @param format Output format
#' @return Rmd template string
#' @keywords internal
generate_report_template <- function(data, title, author, format) {
  template <- sprintf("---
title: '%s'
author: '%s'
date: '%s'
output:
  %s:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ZinaSuite)
library(ggplot2)
```

# Executive Summary

This report was generated by **ZinaSuite** - A Modern R Package for UCSC Xena Data Analysis.

## Analysis Details

- **Date**: %s
- **Format**: %s
- **Package Version**: %s

# Results

```{r results}
# Display analysis results
if (!is.null(data)) {
  print(data)
}
```

# Visualizations

```{r plots, fig.width=10, fig.height=6}
# Generate plots if data contains plot objects
if (is.list(data) && !is.null(data$plot)) {
  print(data$plot)
}
```

# Data Summary

```{r summary}
if (is.data.frame(data)) {
  summary(data)
} else if (is.list(data) && is.data.frame(data$data)) {
  summary(data$data)
}
```

# Session Information

```{r session}
sessionInfo()
```
",
  title,
  author,
  format(Sys.time(), "%Y-%m-%d"),
  format,
  format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
  toupper(format),
  packageVersion("ZinaSuite")
  )

  return(template)
}

#' Export Data to Various Formats
#'
#' @description
#' Export analysis results to CSV, Excel, or JSON format.
#'
#' @param data Data to export
#' @param file Output file path
#' @param format Export format: "csv", "excel", "json", "rds"
#' @param sheet_name Sheet name for Excel (default: "Sheet1")
#' @return Path to exported file
#' @export
#'
#' @examples
#' \dontrun{
#' # Export to CSV
#' data <- query_gene_expression("TP53")
#' export_data(data, "tp53_expression.csv", "csv")
#'
#' # Export to Excel
#' export_data(data, "tp53_expression.xlsx", "excel")
#' }
export_data <- function(data,
                        file = NULL,
                        format = c("csv", "excel", "json", "rds"),
                        sheet_name = "Sheet1") {
  format <- match.arg(format)

  # Auto-determine file extension if not provided
  if (is.null(file)) {
    file <- paste0("export_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".", format)
  }

  # Ensure data is a data frame for tabular formats
  if (format %in% c("csv", "excel") && !is.data.frame(data)) {
    if (is.list(data)) {
      data <- as.data.frame(data)
    } else {
      data <- data.frame(value = data)
    }
  }

  # Export based on format
  switch(format,
         "csv" = {
           utils::write.csv(data, file, row.names = FALSE)
         },
         "excel" = {
           if (!requireNamespace("writexl", quietly = TRUE)) {
             stop("Package 'writexl' is required. Install with: install.packages('writexl')")
           }
           writexl::write_xlsx(data, file)
         },
         "json" = {
           if (!requireNamespace("jsonlite", quietly = TRUE)) {
             stop("Package 'jsonlite' is required. Install with: install.packages('jsonlite')")
           }
           jsonlite::write_json(data, file, pretty = TRUE)
         },
         "rds" = {
           saveRDS(data, file)
         }
  )

  message("Data exported to: ", normalizePath(file))
  invisible(file)
}

#' Batch Export Multiple Datasets
#'
#' @description
#' Export multiple datasets to a single Excel file with multiple sheets.
#'
#' @param data_list Named list of datasets
#' @param file Output Excel file path
#' @return Path to exported file
#' @export
#'
#' @examples
#' \dontrun{
#' # Export multiple datasets
#' data_list <- list(
#'   TP53 = query_gene_expression("TP53"),
#'   BRCA1 = query_gene_expression("BRCA1"),
#'   EGFR = query_gene_expression("EGFR")
#' )
#' batch_export_excel(data_list, "gene_expression.xlsx")
#' }
batch_export_excel <- function(data_list, file = "export.xlsx") {
  if (!requireNamespace("writexl", quietly = TRUE)) {
    stop("Package 'writexl' is required. Install with: install.packages('writexl')")
  }

  if (!is.list(data_list) || is.null(names(data_list))) {
    stop("data_list must be a named list")
  }

  # Convert all elements to data frames
  data_list <- lapply(data_list, function(x) {
    if (!is.data.frame(x)) {
      as.data.frame(x)
    } else {
      x
    }
  })

  # Validate sheet names (Excel has 31 char limit)
  names(data_list) <- substr(names(data_list), 1, 31)

  writexl::write_xlsx(data_list, file)

  message("Batch export complete: ", normalizePath(file))
  message("Sheets: ", paste(names(data_list), collapse = ", "))
  invisible(file)
}

#' Create Analysis Pipeline
#'
#' @description
#' Create a reusable analysis pipeline with multiple steps.
#'
#' @param steps List of analysis functions to apply
#' @param name Pipeline name
#' @return AnalysisPipeline object
#' @export
#'
#' @examples
#' \dontrun{
#' # Create pipeline
#' pipeline <- create_pipeline(list(
#'   query = function(gene) query_gene_expression(gene),
#'   analyze = function(data) analyze_survival_by_expression(data),
#'   visualize = function(result) vis_survival(result)
#' ), name = "Gene Survival Analysis")
#'
#' # Run pipeline
#' result <- run_pipeline(pipeline, gene = "TP53")
#' }
create_pipeline <- function(steps, name = "Analysis Pipeline") {
  structure(
    list(
      name = name,
      steps = steps,
      created = Sys.time()
    ),
    class = "AnalysisPipeline"
  )
}

#' Run Analysis Pipeline
#'
#' @param pipeline AnalysisPipeline object
#' @param ... Arguments passed to first step
#' @return Pipeline results
#' @export
run_pipeline <- function(pipeline, ...) {
  if (!inherits(pipeline, "AnalysisPipeline")) {
    stop("Input must be an AnalysisPipeline object")
  }

  message("Running pipeline: ", pipeline$name)

  result <- list(...)

  for (step_name in names(pipeline$steps)) {
    message("  Executing step: ", step_name)
    step_func <- pipeline$steps[[step_name]]

    tryCatch({
      if (length(result) == 1 && !is.list(result[[1]])) {
        result <- step_func(result[[1]])
      } else {
        result <- do.call(step_func, result)
      }
    }, error = function(e) {
      stop("Error in step '", step_name, "': ", conditionMessage(e))
    })
  }

  message("Pipeline completed successfully")
  return(result)
}

#' Print Analysis Pipeline
#'
#' @param x AnalysisPipeline object
#' @param ... Additional arguments
#' @export
print.AnalysisPipeline <- function(x, ...) {
  cat("Analysis Pipeline: ", x$name, "\n")
  cat("Created: ", format(x$created), "\n")
  cat("Steps:\n")
  for (i in seq_along(x$steps)) {
    cat("  ", i, ". ", names(x$steps)[i], "\n", sep = "")
  }
}
